version: '3.9'
services: 
  web:
    build: .
    ports: 
      - '8000:8000'
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    depends_on:
      - postgres
      - influxdb
    env_file:
      - ./.env

  postgres:
    image: postgres:14.4
    ports: 
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  influxdb:
    image: influxdb:latest
    restart: always
    ports: 
      - '8086:8086'
    volumes:
      - influxdb-storage:/var/lib/influxdb2
    env_file:
      - ./.env

volumes:
  postgres_data:
  influxdb-storage:
