# Generated by Django 4.0.6 on 2022-08-02 17:38

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CryCom', '0002_cryptogroup_teamcoins_groupmembers_blogpost'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogPost',
            new_name='Blog_Post',
        ),
        migrations.RenameModel(
            old_name='CryptoGroup',
            new_name='Crypto_Group',
        ),
        migrations.RenameModel(
            old_name='CryptoValue',
            new_name='Crypto_Value',
        ),
        migrations.RenameModel(
            old_name='GroupMembers',
            new_name='Group_Members',
        ),
        migrations.RenameModel(
            old_name='TeamCoins',
            new_name='Team_Coins',
        ),
    ]
