# Generated by Django 4.0.6 on 2023-03-16 15:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('CryCom', '0003_rename_blogpost_blog_post_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crypto_group',
            name='token',
            field=models.CharField(blank=True, default=uuid.uuid4, max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='group_members',
            name='owner',
            field=models.BooleanField(default=1),
        ),
    ]
