# Generated by Django 4.0.6 on 2023-03-16 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CryCom', '0004_crypto_group_token_group_members_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crypto_group',
            name='crypto_type',
            field=models.TextField(),
        ),
    ]
