# Generated by Django 4.0.6 on 2023-03-23 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CryCom', '0005_alter_crypto_group_crypto_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biggest_Profit_Loss',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('last_week_price', models.FloatField()),
                ('todays_price', models.FloatField()),
                ('difference', models.FloatField()),
            ],
        ),
        migrations.RenameField(
            model_name='team_coins',
            old_name='highest_profit',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='team_coins',
            old_name='quantity',
            new_name='buy_price',
        ),
        migrations.AddField(
            model_name='team_coins',
            name='crypto_name',
            field=models.CharField(default='Null', max_length=20),
        ),
        migrations.AddField(
            model_name='team_coins',
            name='profit',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
