# Generated by Django 4.0.6 on 2023-03-23 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CryCom', '0007_coins_list_coins_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coins_list',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
