# Generated by Django 4.0.6 on 2023-03-23 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CryCom', '0008_alter_coins_list_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Crypto_Value',
        ),
    ]
